# Default values for node-monitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "quay.io/support-tools/monitor-tools:latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name: "node-metrics-sa"

tolerations: 
- operator: Exists

namespace:
  name: "node-metrics"

monitordaemonset:
  name: monitordaemonset
  nodeSelector:
    collect-monitor-sh: ""

metricsdaemonset:
  name: metricsdaemonset
  nodeSelector:
    collect-node-metrics: ""

collectldaemonset:
  name: collectldebug
  nodeSelector:
    run-collectl-debug: ""

collectserviceaccount:
  name: collectldebug

collectlimage:
  name: "quay.io/vwalek/collectl:latest"



